version: 1
labels:
  - label: "upgrade"
    title: "^upgrade"
  - label: "type:sentry"
    title: "^sentry"
  - label: "type:refactoring"
    title: "^ref"
  - label: "type:feature"
    title: "^feat"
  - label: "type:enhancement"
    title: "^enh"
  - label: "type:chore"
    title: "^chore"
  - label: "type:documentation"
    title: "^doc"
  - label: "type:bug"
    title: " fix "
  - label: "type:bug"
    title: " bug "
  - label: "type:bug"
    title: "^fix"
  - label: "project:sso"
    title: '\(sso\)'
  - label: "project:spaces"
    title: '\(spaces\)'
  - label: "project:profile"
    title: '\(profile\)'
  - label: "project:backoffice"
    title: '\(backoffice\)'
  - label: "project:notifications"
    title: '\(notifications\)'
  - label: "project:mentoring"
    title: '\(mentoring\)'
  - label: "project:lms"
    title: '\(lms\)'
  - label: "project:leaderboard"
    title: '\(leaderboard\)'
  - label: "project:hiring"
    title: '\(hiring\)'
  - label: "project:coderhub"
    title: '\(coderhub\)'
  - label: "project:accrediation"
    title: '\(accrediation\)'
  - label: "project:mono-repo"
    title: '\(mono\)'
  - label: "parachute"
    title: "^parachute"
  - label: "design-system"
    title: "^design-system"
  - label: "project:sites"
    title: '\(sites\)'
  - label: "project:satr"
    title: '\(satr\)'
  - label: "project:safcsp-website"
    title: '\(safcsp-website\)'
  - label: "project:coderhub-juniors"
    title: '\(coderhub-juniors\)'
  - label: "project:design-system"
    title: '\(design-system\)'
  - label: "project:short-url"
    title: '\(short-url\)'
