name: Auto Assign

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: ".github/auto_assign.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
