name: Add Reviewers

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          reviewers="F600sa"
          IFS=',' read -r -a reviewers_array <<< "$reviewers"

          for reviewer in "${reviewers_array[@]}"; do
            echo "Attempting to add reviewer: $reviewer"
            gh api \
              --method POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/requested_reviewers \
              -f reviewers='["'"$reviewer"'"]' || true
          done
