name: Auto Assign

on:
  pull_request:
    types: [opened, reopened, ready_for_review, edited, closed]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/auto_assign.yml"
