name: Auto Assign

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
          configuration-path: ".github/auto_assign.yml"
=======
          configuration-path: '.github/auto_assign.yml'
>>>>>>> 64551dd (init)
