name: auto-assign-reviewers-and-assignees

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto_assign:
    name: Auto Assign
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Auto Assign Reviewers and Assignees
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewers="itsReema130"
          assignees="itsReema130"

          # Split the reviewers and assignees into arrays
          IFS=' ' read -r -a reviewers_array <<< "$reviewers"
          IFS=' ' read -r -a assignees_array <<< "$assignees"

          # Add reviewers
          for reviewer in "${reviewers_array[@]}"; do
            echo "Attempting to add reviewer: $reviewer"
            gh pr review-request "${{ github.event.pull_request.number }}" --add "$reviewer" || true
          done

          # Add assignees
          for assignee in "${assignees_array[@]}"; do
            echo "Attempting to add assignee: $assignee"
            gh pr edit "${{ github.event.pull_request.number }}" --add-assignee "$assignee" || true
          done
