name: Add Reviewers

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  request-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Request Reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          reviewers="F600sa,anotheruser"
          reviewers_json=$(jq -n --arg reviewers "$reviewers" '($reviewers | split(","))')

          response=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/requested_reviewers" \
            -d "{\"reviewers\": $reviewers_json}")

          http_code=$(tail -n1 response.json)
          if [[ "$http_code" -ne 201 ]]; then
            echo "Failed to add reviewers. Response:"
            cat response.json
            exit 1
          else
            echo "Reviewers successfully added!"
          fi
