name: open-pull-request-to-master

on:
  push:
    branches:
      - staging

jobs:
  open_pullrequest_to_master:
    name: open pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base master --head staging --title "staging to master" --body "staging to master" --reviewer itsReema130 --assignee itsReema130 | true
